### ISSUE TITLE
refactor the "widget" task and its config initialization

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/grunt-laxar#14]
In order to integrate `grunt-contrib-compass` a little bit of house-keeping is needed.

- [ ] First, any initialization-work should be done in an [init task](https://github.com/gruntjs/grunt/blob/v0.4.5/lib/grunt/task.js#L273). Currenty, the `widget` task creates the Karma and JSHint configuration on-the-fly.
- [ ] The `widget` and `widgets` (the pattern-matching one) tasks should skip tasks that are not applicable for the given widget. That is; if the widget has no `scss` files, don't try to run them and when running `widgets:**:compass` skip those widgets entirely.

**Comment by x1B** [comment]
_Cleared milestone:_ version already out, should be rescheduled

**Comment by x1B** [comment]
_Closing for now:_ situation has changed, right now we are not planning on implementing central SCSS support ourselves.
