### ISSUE TITLE
adopt changes from LaxarJS/laxar#130

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/grunt-laxar#40]

**Comment by alex3683** [comment]
The changes from LaxarJS/laxar#130 have impact onto the tasks `portal_angular_dependencies` and `css_merger`.  All usages have to be adjusted accordingly.

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0`).

## Breaking Change

Starting with this change `grunt-laxar` requires `laxar` `v1.0.0-alpha.5` as minimum version.

**Comment by x1B** [comment]
Look good to me :ok_hand:
