### ISSUE TITLE
Identify controls based on control.json

### ISSUE THREAD

**Issue by x1B** [LaxarJS/grunt-laxar#50]
For LaxarJS/laxar#197 to work, the correct laxar_application_dependencies need to be generated, by using the control.json to identify the control name.

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0`).

### Upgrade Information

Whenever a `control.json` is found under the path given in the `controls` field of a `widget.json`, the `name` property found there will be appended to the information from the `controls` field to derive the name of the actual file of the control's module.

Assume the widget.json looks like this:
```
{
   "name": "TestWidget",
   "integration": {
      "technology": "angular"
   },

   "controls": [
      "my_ui_package/someControl",
      "laxar-path-controls/test-control"
   ]
}
```

If `test-control` has a control json with name "TestControl", its resulting require path will be `laxar-path-controls/test-control/test-control`. On the other hand, if `someControl` doesn't have a control.json, its pat will be `my_ui_package/someControl`.
