### ISSUE TITLE
documentation: configuring additional widget resources

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/grunt-laxar#68]
The possibility to configure additional widget resources for watching, embedding and listing within the `widget.json` isn't documented yet.

**Comment by x1B** [comment]
Implemented on `master` (`v1.1.0`).

### Upgrade Information

Additional documentation for the _laxar-artifacts_ task is available in the [laxar-artifacts  task manual](https://github.com/LaxarJS/grunt-laxar/blob/master/docs/tasks/internal/laxar-artifacts.md).
