### ISSUE TITLE
ax-configure-watch: filter out watching for bower components (configurable)

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/grunt-laxar#78]
Widgets installed as bower package should, by default, not be watched for modifications. Nevertheless it should be possible to enable watching bower packages via configuration.

**Comment by x1B** [comment]
Implemented on `master` (`v1.1.0`).

### Upgrade Information

By default, the grunt-laxar development server no longer watches for changes to anything installed as a Bower component. This saves CPU cycles. To change this, you can add the following task configuration to your Gruntfile:

```js
      'laxar-configure-watch': {
         options: {
            watchBowerComponents: true
         }
      },
```
