### ISSUE TITLE
integration: allow to install widgets using bower

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/grunt-laxar#79]
This is the accompanying *grunt-laxar* ticket to LaxarJS/laxar#129

**Comment by alex3683** [comment]
### Upgrade Information

See LaxarJS/laxar#129 for further information.

**Comment by x1B** [comment]
@alex3683 looking good, back to you

**Comment by x1B** [comment]
One note though: As far as I can see, this only covers widgets, which can now be installed through "local:X" (which equals just "X") as well as "amd:Y".

The ticket LaxarJS/laxar#129 also talks about other artifacts (especially controls), so we should explain the restriction in the upgrade information, or modify LaxarJS/laxar#129

**Comment by alex3683** [comment]
Implemented on `master` (`v1.1.0`).

### Upgrade Information

See LaxarJS/laxar#129 for further information.
