### ISSUE TITLE
laxar-test: Tries to scan the directory 'includes/themes' and aborts 

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/grunt-laxar#82]
When executing `laxar-test` the script `laxar-artifacts:main` tries to scan the directory `includes/themes` and aborts if it doesn't exist.

**Comment by x1B** [comment]
Problem was introduced post-`v1.0.0`.

**Comment by x1B** [comment]
Fixed on `master` (`v1.1.0`)
