### ISSUE TITLE
fixinstall: throws ENOENT when using npm 3.x

### ISSUE THREAD

**Issue by x1B** [LaxarJS/grunt-laxar#87]
The `fixinstall` script provided by grunt-laxar tries to detect and fix broken PhantomJS module installations. With npm v3.x, the node_modules directory layout has changed and the fixinstall script runs into problems.

**Comment by x1B** [comment]
@jpommerening r? commit 7408639

**Comment by x1B** [comment]
The new "solution" does not try to fix the installation when using npm 3+ since we just assume it will work there.

**Comment by jpommerening** [comment]
@x1B lgtm :+1:

**Comment by x1B** [comment]
Thx! :rainbow: :sparkles:

**Comment by x1B** [comment]
Fixed on `master` (`v1.1.0`) and `release-1.0.x` (`v1.0.3`).
